-- ============================================================
-- Short-Term Trading System Tables
-- Additional tables for short-term strategy
-- ============================================================

-- Price History Table
-- Store OHLCV data for technical analysis
CREATE TABLE IF NOT EXISTS price_history (
    id SERIAL PRIMARY KEY,
    ticker_code VARCHAR(20) NOT NULL,
    date TIMESTAMP NOT NULL,
    open DECIMAL(15, 2) NOT NULL,
    high DECIMAL(15, 2) NOT NULL,
    low DECIMAL(15, 2) NOT NULL,
    close DECIMAL(15, 2) NOT NULL,
    volume BIGINT DEFAULT 0,
    adjusted_close DECIMAL(15, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(ticker_code, date)
);

CREATE INDEX idx_price_history_ticker_date ON price_history(ticker_code, date DESC);
CREATE INDEX idx_price_history_date ON price_history(date DESC);

COMMENT ON TABLE price_history IS 'Historical OHLCV price data for technical analysis';
COMMENT ON COLUMN price_history.ticker_code IS 'Stock ticker code';
COMMENT ON COLUMN price_history.date IS 'Trading date/time';
COMMENT ON COLUMN price_history.open IS 'Opening price';
COMMENT ON COLUMN price_history.high IS 'Highest price';
COMMENT ON COLUMN price_history.low IS 'Lowest price';
COMMENT ON COLUMN price_history.close IS 'Closing price';
COMMENT ON COLUMN price_history.volume IS 'Trading volume';


-- Trade Metadata Table
-- Store strategy-specific trade metadata
CREATE TABLE IF NOT EXISTS trade_metadata (
    id SERIAL PRIMARY KEY,
    trade_id INTEGER NOT NULL REFERENCES trade_history(id) ON DELETE CASCADE,
    strategy_type VARCHAR(50) NOT NULL,  -- 'short_term' or 'growth'
    entry_signal_score DECIMAL(5, 2),
    technical_score DECIMAL(5, 2),
    sentiment_score DECIMAL(5, 2),
    exit_signal_score DECIMAL(5, 2),
    holding_hours DECIMAL(10, 2),
    metadata JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(trade_id)
);

CREATE INDEX idx_trade_metadata_trade ON trade_metadata(trade_id);
CREATE INDEX idx_trade_metadata_strategy ON trade_metadata(strategy_type);

COMMENT ON TABLE trade_metadata IS 'Strategy-specific metadata for trades';
COMMENT ON COLUMN trade_metadata.strategy_type IS 'Trading strategy (short_term/growth)';
COMMENT ON COLUMN trade_metadata.entry_signal_score IS 'Signal score at entry';
COMMENT ON COLUMN trade_metadata.technical_score IS 'Technical analysis score';
COMMENT ON COLUMN trade_metadata.sentiment_score IS 'Sentiment analysis score';


-- Strategy Performance Table
-- Track performance by strategy type
CREATE TABLE IF NOT EXISTS strategy_performance (
    id SERIAL PRIMARY KEY,
    strategy_type VARCHAR(50) NOT NULL,
    date DATE NOT NULL,
    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    total_pnl DECIMAL(15, 2) DEFAULT 0,
    avg_pnl_pct DECIMAL(10, 4),
    win_rate DECIMAL(5, 2),
    avg_holding_hours DECIMAL(10, 2),
    max_drawdown DECIMAL(10, 4),
    sharpe_ratio DECIMAL(10, 4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(strategy_type, date)
);

CREATE INDEX idx_strategy_performance_type_date ON strategy_performance(strategy_type, date DESC);

COMMENT ON TABLE strategy_performance IS 'Daily performance metrics by strategy';


-- Intraday Signals Table
-- Store short-term trading signals for analysis
CREATE TABLE IF NOT EXISTS intraday_signals (
    id SERIAL PRIMARY KEY,
    ticker_code VARCHAR(20) NOT NULL,
    signal_type VARCHAR(20) NOT NULL,  -- 'BUY', 'SELL', 'NEUTRAL'
    signal_score DECIMAL(5, 2) NOT NULL,
    confidence DECIMAL(5, 4) NOT NULL,
    technical_indicators JSONB,
    sentiment_data JSONB,
    momentum_data JSONB,
    is_executed BOOLEAN DEFAULT FALSE,
    executed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP
);

CREATE INDEX idx_intraday_signals_ticker ON intraday_signals(ticker_code);
CREATE INDEX idx_intraday_signals_created ON intraday_signals(created_at DESC);
CREATE INDEX idx_intraday_signals_type ON intraday_signals(signal_type);

COMMENT ON TABLE intraday_signals IS 'Short-term trading signals generated by the system';
COMMENT ON COLUMN intraday_signals.signal_type IS 'Signal direction (BUY/SELL/NEUTRAL)';
COMMENT ON COLUMN intraday_signals.expires_at IS 'Signal expiration time';


-- Market Conditions Table
-- Track overall market conditions for strategy adjustments
CREATE TABLE IF NOT EXISTS market_conditions (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    market_index VARCHAR(20),  -- 'NIKKEI', 'SPX', etc.
    index_value DECIMAL(15, 2),
    index_change_pct DECIMAL(10, 4),
    volatility_index DECIMAL(10, 4),  -- VIX equivalent
    market_sentiment VARCHAR(20),  -- 'BULLISH', 'BEARISH', 'NEUTRAL'
    trend VARCHAR(20),  -- 'UPTREND', 'DOWNTREND', 'SIDEWAYS'
    volume_ratio DECIMAL(10, 4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(market_index, date)
);

CREATE INDEX idx_market_conditions_date ON market_conditions(date DESC);
CREATE INDEX idx_market_conditions_index ON market_conditions(market_index);

COMMENT ON TABLE market_conditions IS 'Overall market conditions and sentiment';


-- Views for quick analysis

-- Active Short-Term Positions View
CREATE OR REPLACE VIEW v_active_short_term_positions AS
SELECT
    th.id as trade_id,
    th.ticker_code,
    th.entry_price,
    th.quantity,
    th.entry_date,
    EXTRACT(EPOCH FROM (NOW() - th.entry_date)) / 3600 as holding_hours,
    tm.entry_signal_score,
    tm.technical_score,
    tm.sentiment_score,
    th.notes
FROM trade_history th
LEFT JOIN trade_metadata tm ON th.id = tm.trade_id
WHERE th.status = 'OPEN'
  AND tm.strategy_type = 'short_term'
ORDER BY th.entry_date DESC;

COMMENT ON VIEW v_active_short_term_positions IS 'Currently active short-term trading positions';


-- Short-Term Performance View
CREATE OR REPLACE VIEW v_short_term_performance AS
SELECT
    DATE(th.exit_date) as trade_date,
    COUNT(*) as trades,
    SUM(CASE WHEN th.pnl > 0 THEN 1 ELSE 0 END) as wins,
    SUM(CASE WHEN th.pnl <= 0 THEN 1 ELSE 0 END) as losses,
    ROUND(AVG(th.pnl_percentage), 2) as avg_return_pct,
    SUM(th.pnl) as total_pnl,
    ROUND(AVG(EXTRACT(EPOCH FROM (th.exit_date - th.entry_date)) / 3600), 1) as avg_holding_hours
FROM trade_history th
LEFT JOIN trade_metadata tm ON th.id = tm.trade_id
WHERE th.status = 'CLOSED'
  AND tm.strategy_type = 'short_term'
GROUP BY DATE(th.exit_date)
ORDER BY trade_date DESC;

COMMENT ON VIEW v_short_term_performance IS 'Daily performance summary for short-term strategy';


-- Signal Performance Tracking View
CREATE OR REPLACE VIEW v_signal_performance AS
SELECT
    CASE
        WHEN tm.entry_signal_score >= 80 THEN 'Very High (80+)'
        WHEN tm.entry_signal_score >= 70 THEN 'High (70-79)'
        WHEN tm.entry_signal_score >= 60 THEN 'Medium (60-69)'
        ELSE 'Low (<60)'
    END as signal_strength,
    COUNT(*) as total_trades,
    SUM(CASE WHEN th.pnl > 0 THEN 1 ELSE 0 END) as winning_trades,
    ROUND(AVG(th.pnl_percentage), 2) as avg_return_pct,
    ROUND(SUM(th.pnl), 0) as total_pnl
FROM trade_history th
JOIN trade_metadata tm ON th.id = tm.trade_id
WHERE th.status = 'CLOSED'
  AND tm.strategy_type = 'short_term'
GROUP BY signal_strength
ORDER BY MIN(tm.entry_signal_score) DESC;

COMMENT ON VIEW v_signal_performance IS 'Performance breakdown by entry signal strength';
